- name: "1.1.1.1 | Ensure mounting of cramfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install cramfs(\\s|$)"
      line: "install cramfs /bin/true"
      create: yes
  tags:
      - id_1.1.1.1

- name: "1.1.1.2 | Ensure mounting of freevxfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install freevxfs(\\s|$)"
      line: "install freevxfs /bin/true"
      create: yes
  tags:
      - id_1.1.1.2

- name: "1.1.1.3 | Ensure mounting of jffs2 filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install jffs2(\\s|$)"
      line: "install jffs2 /bin/true"
      create: yes
  tags:
      - id_1.1.1.3

- name: "1.1.1.4 | Ensure mounting of hfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfs(\\s|$)"
      line: "install hfs /bin/true"
      create: yes
  tags:
      - id_1.1.1.4

- name: "1.1.1.5 | Ensure mounting of hfsplus filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfsplus(\\s|$)"
      line: "install hfsplus /bin/true"
      create: yes
  tags:
      - id_1.1.1.5

- name: "1.1.1.6 | Ensure mounting of squashfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install squashfs(\\s|$)"
      line: "install squashfs /bin/true"
      create: yes
  tags:
      - id_1.1.1.6

- name: "1.1.1.7 | Ensure mounting of udf filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install udf(\\s|$)"
      line: "install udf /bin/true"
      create: yes
  tags:
      - id_1.1.1.7

- name: "1.1.1.8 | Ensure mounting of FAT filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install vfat(\\s|$)"
      line: "install vfat /bin/true"
      create: yes
  tags:
      - id_1.1.1.8

- name: "1.1.21 | Set Sticky Bit on All World-Writable Directories"
  shell: df --local -P| awk {'if (NR!=1) print $6'}| xargs -I '{}' find '{}' -xdev -type d -perm -0002 -print 2>/dev/null
  failed_when: False
  changed_when: False
  check_mode: no
  register: sticky_bit_dirs
  tags:
    - id_1.1.21

- name: "1.1.22 | Disable Automounting"
  service:
      name: autofs
      enabled: no
  when: autofs_service_status.stdout == "loaded"
  tags:
      - id_1.1.22

- name: "1.2.2 | Ensure gpgcheck is globally activated"
  replace:
      name: /etc/yum.conf
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
  tags:
      - id_1.2.2

- name: "1.2.2 | Ensure gpgcheck is globally activated"
  find:
      paths: /etc/yum.repos.d
      patterns: "*.repo"
  register: yum_repos
  changed_when: no
  tags:
      - id_1.2.2

- name: "1.2.2 | Ensure gpgcheck is globally activated"
  replace:
      name: "{{ item.path }}"
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
  with_items:
      - "{{ yum_repos.files }}"
  tags:
      - id_1.2.2

- name: "1.2.5 | Disable the rhnsd Daemon"
  service:
      name: rhnsd
      state: stopped
      enabled: no
  when: ansible_distribution == "RedHat" and rhnsd_service_status and not rhel7gsa_rhnsd_required
  tags:
      - id_1.2.5


- name: "1.3.1 | Ensure AIDE is installed"
  yum:
      name: aide
      state: present
  when: rhel7gsa_config_aide == "true"
  tags:
      - aide
      - id_1.3.1

- name: "1.3.1 | Ensure AIDE is installed"
  command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  args:
      creates: /var/lib/aide/aide.db.gz
  when: rhel7gsa_config_aide == true
  async: 45
  poll: 0
  tags:
      - aide
      - id_1.3.1

- name: "1.3.2 | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check weekly
      cron_file: "{{ rhel7gsa_aide_cron['cron_file'] }}"
      user: "{{ rhel7gsa_aide_cron['cron_user'] }}"
      minute: "{{ rhel7gsa_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ rhel7gsa_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ rhel7gsa_aide_cron['aide_day'] | default('*') }}"
      month: "{{ rhel7gsa_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ rhel7gsa_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ rhel7gsa_aide_cron['aide_job'] }}"
  when: rhel7gsa_config_aide == true
  tags:
      - scored
      - aide
      - file_integrity
      - rule_1.3.2

- name: "1.4.1 | Ensure permissions on bootloader config are configured"
  stat:
      path: /etc/grub2.cfg
  register: grub_cfg
  tags:
      - grub
      - id_1.4.1

- name: "1.4.1 | Ensure permissions on bootloader config are configured"
  file:
      path: "{{ grub_cfg.stat.lnk_source }}"
      owner: root
      group: root
      mode: 0600
  when: grub_cfg.stat.exists and grub_cfg.stat.islnk
  tags:
      - grub
      - id_1.4.1

- name: "1.5.1 | Ensure core dumps are restricted"
  lineinfile:
      state: present
      dest: /etc/security/limits.conf
      regexp: '^#?\\*.*core'
      line: '*                hard    core            0'
      insertbefore: '^# End of file'
  tags:
      - limits
      - id_1.5.1

- name: "1.5.1 | Ensure core dumps are restricted"
  sysctl:
      name: fs.suid_dumpable
      value: 0
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  tags:
      - sysctl
      - id_1.5.1

- name: "1.5.3 | Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: kernel.randomize_va_space
      value: 2
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  tags:
      - id_1.5.3

- name: "1.5.4 | Ensure prelink is disabled"
  yum:
    name: prelink
    state: absent
  tags:
      - id_1.5.4

- name: "1.6.1.1 | Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
      follow: yes
  register: selinux_grub_patch
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
  notify: generate new grub config
  tags:
      - id_1.6.1.1

- name: "1.6.1.2 & 1.6.1.3 | Ensure the SELinux state is enforcing"
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
  selinux:
      policy: targeted
      state: enforcing
  tags:
      - selinux
      - id_1.6.1.2
      - id_1.6.1.3

- name: "1.6.1.4 | Ensure SETroubleshoot is not installed"
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
  yum:
      name: setroubleshoot
      state: absent
  tags:
      - selinux
      - id_1.6.1.4

- name: "1.6.1.5 | Ensure the MCS Translation Service (mcstrans) is not installed"
  yum:
      name: mcstrans
      state: absent
  tags:
      - id_1.6.1.5

- name: "1.6.2 | Ensure SELinux is installed"
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
  yum:
      name: libselinux
      state: present
  tags:
      - id_1.6.2

- name: "1.7.1.1 | Ensure message of the day is configured properly"
  template:
      src: motd.j2
      dest: /etc/motd
  tags:
      - banner
      - id_1.7.1.1

- name: "1.7.1.2 | Ensure local login warning banner is configured properly"
  template:
      src: issue.j2
      dest: /etc/issue
  tags:
      - id_1.7.1.2

- name: "1.7.1.3 | Ensure remote login warning banner is configured properly"
  template:
      src: issue.net.j2
      dest: /etc/issue.net
  tags:
      - id_1.7.1.3

- name: "1.7.1.4 | Ensure permissions on /etc/motd are configured"
  file:
      dest: /etc/motd
      state: file
      owner: root
      group: root
      mode: 0644
  tags:
      - perms
      - id_1.7.1.4

- name: "1.7.1.5 | Ensure permissions on /etc/issue are configured"
  file:
      dest: /etc/issue
      state: file
      owner: root
      group: root
      mode: 0644
  tags:
      - perms
      - id_1.7.1.5

- name: "1.7.1.6 | Ensure permissions on /etc/issue.net are configured"
  file:
      dest: /etc/issue.net
      state: file
      owner: root
      group: root
      mode: 0644
  tags:
      - perms
      - id_1.7.1.6

- name: "1.8 | Ensure updates, patches, and additional security software are installed"
  yum:
      name: "*"
      state: latest
  tags:
      - id_1.8
